version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3001:3000
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - 8001:8000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_data:
